ODD_OR_EVEN:       MOV P0, #0FFH
                   MOV A, P0
                   LCALL PRINT_DATA
                   MOV R1,#01h
GET_P:             CJNE R1, #0FH, NEXT
                   LCALL CLEFT
NEXT:              MOV R0, A    
                   LCALL SEND_DATA
                   INC R1
 
CHECK_ODD:         MOV P0, #0FFH
                   MOV A,P0
                   MOV 12H,R0
                   CJNE A, 12H, GET_P
                   SJMP CHECK

CLEFT:             MOV A,#04H;move cursor to the left
                   ACALL COMNWRT
                   ACALL DELAY

CLR_SCR:           CLR A
                   MOV A,#20H     ;LOAD A, THE ASCII NUMBER CORRESPONDING TO THE CHARACTER
                   ACALL DATAWRT  ;WHEN SENDING DATA TO DISPLAY, USE DATAWRT  SUBROUTINE
                   ACALL DELAY    ;GIVE LCD SOME TIME
				   ACALL DELAY_500ms
				   DJNZ R1, CLR_SCR
				   LJMP ASCII_WRITER
 
     
   
PRINT_DATA:
;THIS FIRST PART SENDS THE INITIALIZATION COMMANDS TO THE LCD
MOV A,#38H;TWO LINES, 5X7 MATRIX
ACALL COMNWRT  ;WHEN SENDING A COMMAND, USE COMNWRT SUBROUTINE
ACALL DELAY    ;GIVE LCD SOME TIME


MOV A,#0FH;DISPLAY ON, CURSOR BLINKING
ACALL COMNWRT
ACALL DELAY


MOV A,#01H;CLEAR DISPLAY SCREEN
ACALL COMNWRT
ACALL DELAY


MOV A,#06H;INCREMENT CURSOR (SHIFT CURSOR TO RIGHT)
ACALL COMNWRT
ACALL DELAY


MOV A,#80H;FORCE CURSOR TO BEGINNING OF THE FIRST LINE
ACALL COMNWRT
ACALL DELAY
RET

SEND_DATA:
;SENDING THE ASCII DATA	TO THE SCREEN
CLR A
MOV A,R0     ;LOAD A, THE ASCII NUMBER CORRESPONDING TO THE CHARACTER
ACALL DATAWRT  ;WHEN SENDING DATA TO DISPLAY, USE DATAWRT  SUBROUTINE
ACALL DELAY    ;GIVE LCD SOME TIME
RET



;P1.0-P1.7 ARE CONNECTED TO LCD DATA PINS D0-D7
;P3.2 IS CONNECTED TO RS PIN 
;P3.3 IS CONNECTED TO R/W PIN
;P3.4 IS CONNECTED TP E PIN


COMNWRT:    ;THIS  SUBROUTINE IS FOR SENDING THE COMMANDS TO LCD
MOV P1,A    ;THE COMMAND IS STORED IN A, SEND IT TO LCD
CLR P3.2    ;RS=0 BEFORE SENDING COMMAND
CLR P3.3    ;R/W=0 TP WRITE
SETB P3.4;SEND A HIGH TO LOW SIGNAL TO ENABLE PIN
ACALL DELAY
CLR P3.4
RET


DATAWRT:    ;THIS  SUBROUTINE IS FOR SENDING THE DATA TO BE DISPLAYED
MOV P1,A    ;SEND THE DATA STORED IN A TO LCD
SETB P3.2   ;RS=1 BEFORE SENDING DATA
CLR P3.3 ;R/W=0 TP WRITE
SETB P3.4;SEND A HIGH TO LOW SIGNAL TO ENABLE PIN
ACALL DELAY
CLR P3.4
RET


DELAY: MOV R3,#50
LOOP3: MOV R4,#255
LOOP4: DJNZ R4,LOOP4
DJNZ R3,LOOP3
RET


DELAYhsec:
	   MOV R5,#22
LOOP0: MOV R3,#248
LOOP1: MOV R4,#255
LOOP2: DJNZ R4,LOOP2
	   DJNZ R3,LOOP1
       DJNZ R5,LOOP0
RET




END

